#ifndef __STATİCPROCESS_H_
#define __STATİCPROCESS_H_



typedef enum{
  SETALARM_STATE_SEND_HOUR,
  SETALARM_STATE_OPERATION_HOUR,
  SETALARM_STATE_SEND_MINUTE,
  SETALARM_STATE_OPERATION_MINUTE,
  SETALARM_STATE_SEND_ALARMTIME
}en_setalarm_state;

typedef enum 
{
  SETTIME_STATE_SEND_HOUR,
  SETTIME_STATE_OPERATION_HOUR,
  SETTIME_STATE_SEND_MINUTE,
  SETTIME_STATE_OPERATION_MINUTE,
  SETTIME_STATE_SEND_SECOND,
  SETTIME_STATE_OPERATION_SECOND,
  SETTIME_STATE_SEND_DAY,
  SETTIME_STATE_OPERATION_DAY,
  SETTIME_STATE_SEND_MONTH,
  SETTIME_STATE_OPERATION_MONTH,
  SETTIME_STATE_SEND_YEAR,
  SETTIME_STATE_OPERATION_YEAR
}en_settime_state;

typedef enum {
  SETTOUCH_STATE_IDLE,
  SETTOUCH_STATE_PASSWORD,
  SETTOUCH_STATE_TEMP,
  SETTOUCH_STATE_SLEEP,
  SETTOUCH_STATE_TIME,
  SETTOUCH_STATE_ALARM,
  SETTOUCH_STATE_CHANGE_PASSWORD
}en_settouch_state;


#endif